name: Test

on:
    push:
        branches: [master]
    pull_request:

jobs:
    test:
        name: Test
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                go-version: [1.22.x]

        runs-on: ${{ matrix.os }}
        env:
            COVERPROFILE: ./cover.out
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Test and Coverage
              shell: bash
              run: |
                make up
                make test

            - name: Coveralls
              uses: shogo82148/actions-goveralls@v1
              with:
                  path-to-profile: ${{ env.COVERPROFILE }}

    semantic-release:
        name: Semantic Release
        runs-on: ubuntu-latest
        needs: [test]
        if: github.event_name == 'push'
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
            - name: Run semantic-release
              run: |
                  yarn global add semantic-release@17
                  semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
