name: Test

on:
    push:
        branches: [master]
    pull_request:

jobs:
    test:
        name: Test
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                go-version: [1.22.x]

        runs-on: ${{ matrix.os }}
        env:
            COVERPROFILE: ${{ github.workspace }}/cover.out
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Test and Coverage
              shell: bash
              run: |
                make test

            - name: Coveralls
              uses: shogo82148/actions-goveralls@v1
              with:
                  path-to-profile: ${{ env.COVERPROFILE }}