name: Release

on:
    workflow_dispatch: 
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '[a-z]+/v[0-9]+.[0-9]+.[0-9]+'
    workflow_run:
        workflows: ["Test"]
        branches: [master]
        types: [completed]

jobs:
    semantic-release:
        name: Semantic Release
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
        strategy:
            fail-fast: false
            matrix:
              include:
                - directory: '.'
                  tag-format: ${{ format('v{{0}}', 'version') }}
                - directory: 'redis'
                  tag-format: ${{ format('redis/v{{0}}', 'version') }}
                - directory: 'rediscluster'
                  tag-format: ${{ format('rediscluster/v{{0}}', 'version') }}
                - directory: 'ramcache'
                  tag-format: ${{ format('ramcache/v{{0}}', 'version') }}
                - directory: 'memcache'
                  tag-format: ${{ format('memcache/v{{0}}', 'version') }}
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  sparse-checkout: |
                        ${{ matrix.directory }}
            - name: 'Run semantic-release in "${{ matrix.directory }}"'
              working-directory: ${{ matrix.directory }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn global add semantic-release@17
                  semantic-release --tag-format ${{ matrix.tag-format }}
